
title: Notus JS
description: notus-js project by creative-tim remaked 
baseurl: "/notus-js" 
url: "https://demos.creative-tim.com" 

twitter_path: https://twitter.com/intent/tweet?url=https%3A%2F%2Fdemos.creative-tim.com%2Fnotus-js%2F&text=Start%20your%20development%20with%20a%20Free%20Tailwind%20CSS%20and%20JavaScript%20UI%20Kit%20and%20Admin.%20Let%20Notus%20JS%20amaze%20you%20with%20its%20cool%20features%20and%20build%20tools%20and%20get%20your%20project%20to%20a%20whole%20new%20level.
facebook_path: https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdemos.creative-tim.com%2Fnotus-js%2F
github_path: https://github.com/creativetimofficial/notus-js?ref=njs-index

#Build settings
theme: minima
permalink: pretty
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-autoprefixer

exclude:
  - Gemfile
  - Gemfile.lock

